export const TECH_STACK_CONSTANTS = {
  section: {
    number: "001",
    title: "Technical Skills",
    description:
      "Focused on delivering high-performance web applications with modern technologies. Committed to continuous learning and best practices.",
  },
  categories: {
    frontend: {
      icon: "Laptop",
      title: "FRONTEND DEVELOPMENT",
      description: "Specializing in modern, user-centric web applications",
      skills: [
        {
          name: "TYPESCRIPT",
          level: "Advanced",
          proficiency: "4+ years of production experience",
          icon: "SiTypescript",
          iconColor: "text-blue-500 dark:text-blue-400",
          details: "Type-safe development, advanced patterns, and complex state management",
        },
        {
          name: "REACT",
          level: "Advanced",
          proficiency: "Enterprise-level applications",
          icon: "SiReact",
          iconColor: "text-blue-400 dark:text-blue-300",
          details: "Custom hooks, performance optimization, and complex component architecture",
        },
        {
          name: "NEXT.JS",
          level: "Advanced",
          proficiency: "Full-stack applications",
          icon: "SiNextdotjs",
          iconColor: "text-black dark:text-white",
          details: "Server components, streaming, and advanced routing patterns",
        },
        {
          name: "HTML/CSS",
          level: "Advanced",
          proficiency: "Semantic markup and modern CSS",
          icon: "Code2",
          iconColor: "text-orange-500 dark:text-orange-400",
          details: "Accessibility, responsive design, and modern CSS features",
        },
        {
          name: "TAILWIND",
          level: "Advanced",
          proficiency: "Utility-first development",
          icon: "Code2",
          iconColor: "text-cyan-500 dark:text-cyan-400",
          details: "Custom configurations, component design, and responsive layouts",
        },
      ],
    },
    backend: {
      icon: "Database",
      title: "BACKEND DEVELOPMENT",
      description: "Building scalable server-side solutions",
      skills: [
        {
          name: "NODE.JS",
          level: "Proficient",
          proficiency: "Production microservices",
          icon: "SiNodedotjs",
          iconColor: "text-emerald-500 dark:text-emerald-400",
          details:
            "Event-driven architecture, performance optimization, and security best practices",
        },
        {
          name: "EXPRESS",
          level: "Proficient",
          proficiency: "REST API development",
          icon: "SiExpress",
          iconColor: "text-zinc-500 dark:text-zinc-300",
          details: "Middleware patterns, error handling, and API security",
        },
        {
          name: "BUN",
          level: "Intermediate",
          proficiency: "High-performance applications",
          icon: "Code2",
          iconColor: "text-purple-500 dark:text-purple-400",
          details: "Fast runtime, built-in bundler, and TypeScript support",
        },
        {
          name: "WEBSOCKETS",
          level: "Proficient",
          proficiency: "Real-time applications",
          icon: "Code2",
          iconColor: "text-green-500 dark:text-green-400",
          details: "Bi-directional communication, scaling strategies, and fallback mechanisms",
        },
      ],
    },
    database: {
      icon: "Layers",
      title: "DATABASE & INFRASTRUCTURE",
      description: "Database design and infrastructure management",
      skills: [
        {
          name: "POSTGRESQL",
          level: "Proficient",
          proficiency: "Production databases",
          icon: "Database",
          iconColor: "text-blue-500 dark:text-blue-400",
          details: "Query optimization, indexing strategies, and data modeling",
        },
        {
          name: "SUPABASE",
          level: "Proficient",
          proficiency: "Full-stack integration",
          icon: "SiSupabase",
          iconColor: "text-emerald-500 dark:text-emerald-400",
          details: "Real-time subscriptions, row-level security, and edge functions",
        },
        {
          name: "REDIS",
          level: "Intermediate",
          proficiency: "Caching & queuing",
          icon: "SiRedis",
          iconColor: "text-red-500 dark:text-red-400",
          details: "Caching strategies, pub/sub patterns, and session management",
        },
      ],
    },
    cloud: {
      icon: "Cloud",
      title: "CLOUD & DEVOPS",
      description: "Cloud infrastructure and deployment automation",
      skills: [
        {
          name: "AWS",
          level: "Intermediate",
          proficiency: "Cloud infrastructure",
          icon: "Code2",
          iconColor: "text-orange-500 dark:text-orange-400",
          details: "EC2, S3, Lambda, and infrastructure as code",
        },
        {
          name: "DIGITAL OCEAN",
          level: "Intermediate",
          proficiency: "Cloud hosting",
          icon: "Code2",
          iconColor: "text-blue-500 dark:text-blue-400",
          details: "Droplets, managed databases, and container orchestration",
        },
        {
          name: "DOCKER",
          level: "Intermediate",
          proficiency: "Container orchestration",
          icon: "SiDocker",
          iconColor: "text-blue-400 dark:text-blue-300",
          details: "Containerization, multi-stage builds, and compose workflows",
        },
      ],
    },
  },
} as const;
